/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/softPopTheme.ts
 * Command: astryx theme build src/theme/softPopTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const softPopTheme: DefinedTheme;
